name: CI

on:
  push:
    branches:
      - main
      - alpha
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build editor
        run: npm run editor:build

      - name: Lint files
        run: npm run lint

      - name: Typecheck files
        run: npm run typecheck

  build-library:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build editor
        run: npm run editor:build

      - name: Build package
        run: npm run prepack

  build-android:
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      TURBO_CACHE_DIR: .turbo/android
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Cache turborepo for Android
        uses: actions/cache@v5.0.3
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turborepo-android-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-turborepo-android-

      - name: Check turborepo cache for Android
        run: |
          TURBO_CACHE_STATUS=$(node -p "($(npx turbo run build:android --cache-dir="${{ env.TURBO_CACHE_DIR }}" --dry=json)).tasks.find(t => t.task === 'build:android').cache.status")

          if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
            echo "turbo_cache_hit=1" >> $GITHUB_ENV
          fi

      - name: Install JDK
        if: env.turbo_cache_hit != 1
        uses: actions/setup-java@v5.2.0
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Finalize Android SDK
        if: env.turbo_cache_hit != 1
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Cache Gradle
        if: env.turbo_cache_hit != 1
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('examplelatest/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build example for Android
        run: |
          npx turbo run build:android --cache-dir="${{ env.TURBO_CACHE_DIR }}"

  build-ios:
    runs-on: macos-latest
    needs: [lint]
    env:
      TURBO_CACHE_DIR: .turbo/ios
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Cache turborepo for iOS
        uses: actions/cache@v5.0.3
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turborepo-ios-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-turborepo-ios-

      - name: Check turborepo cache for iOS
        run: |
          TURBO_CACHE_STATUS=$(node -p "($(npx turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}" --dry=json)).tasks.find(t => t.task === 'build:ios').cache.status")

          if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
            echo "turbo_cache_hit=1" >> $GITHUB_ENV
          fi

      - name: Cache cocoapods
        if: env.turbo_cache_hit != 1
        id: cocoapods-cache
        uses: actions/cache@v5.0.3
        with:
          path: |
            **/ios/Pods
          key: ${{ runner.os }}-cocoapods-v3-${{ hashFiles('examplelatest/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-v3-

      - name: Install cocoapods
        if: env.turbo_cache_hit != 1 && steps.cocoapods-cache.outputs.cache-hit != 'true'
        run: |
          npx pod-install examplelatest/ios
        env:
          NO_FLIPPER: 1

      - name: Build example for iOS
        run: |
          npx turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}"

  release:
    runs-on: ubuntu-latest
    needs: [build-library, build-android, build-ios]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/alpha')
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build editor bundle
        run: npm run editor:build

      - name: Build web utils
        run: npm run editor:build-web-utils

      - name: Build package
        run: npm run prepack

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_CONFIG_PROVENANCE: "true"
